# Generated by Django 4.0.3 on 2022-04-09 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_joined_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'CUSTOMER'), ('SALESREP', 'SALES REPRESENTATIVE'), ('SALESMANAG', 'SALES MANAGER'), ('TECH', 'SERVICE TECHNICIAN'), ('ENG', 'ENGINEER'), ('SUPUSR', 'SUPER USER'), ('CEO', 'CEO')], default='CUSTOMER', max_length=256),
        ),
    ]
