# Generated by Django 4.0.3 on 2022-04-27 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_brand_created_at_measurementcategory_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.brand'),
            preserve_default=False,
        ),
    ]
